// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommandGoal struct {
	ID               string `json:"id"`
	Dog              *Dog   `json:"dog"`
	DogID            string `json:"dogId"`
	BaseCommand      string `json:"baseCommand"`
	Goal             string `json:"goal"`
	DefinitionOfDone string `json:"definitionOfDone"`
	Priority         int    `json:"priority"`
}

type CommandGoalInput struct {
	DogID            string `json:"dogId"`
	BaseCommand      string `json:"baseCommand"`
	Goal             string `json:"goal"`
	DefinitionOfDone string `json:"definitionOfDone"`
	Priority         int    `json:"priority"`
}

type Dog struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	CommandGoals []*CommandGoal `json:"commandGoals,omitempty"`
}

type DogInput struct {
	Name string `json:"name"`
}

type Mutation struct {
}

type Query struct {
}
